### PR TITLE
Chore: Update dependencies

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR upgrades some of our dependencies to their latest versions. I've also removed the dependency override on the markdown package since the package now supports footnotes. For reference, the original issue with markdown is here: https://github.com/thunder-app/thunder/issues/211

@micahmo I looked through the changes for most of the packages, and it seems like a big portion had to do with increasing the `compileSdkVersion` and `gradle` versions for Android. Because of this, do let me know if you encounter any issues running on Android!

## Issue Being Fixed

Issue Number: N/A

## Checklist

- [ ] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Review by micahmo — APPROVED** [review]
LGTM! I will keep an eye out for any issues.

**Comment by micahmo** [comment]
@hjiangsu I've noticed a couple things broken so far.

1. It looks like autocomplete suggestions for input dialogs (community/user/etc.) don't work any more. I did notice some code changes in that area.
2. It looks like the Android back button no longer works to navigate back to the feed page from another page, nor does it show the snackbar on the feed page. It now instantly closes the app in both of those scenarios.

**Comment by micahmo** [comment]
@hjiangsu Quick update. I started looking into the back button issue. It looks like it's related to the upgrade of `GoRouter`, since downgrading it back to `^12.1.1` fixes the issue.

I also know `WillPopScope` is being deprecated; however the alternative, `PopScope`, doesn't seem to be playing nicely with `GoRouter` either (see [here](https://github.com/flutter/flutter/issues/138737)). `canPop: false` is ignored and `onPopInvoked` is never called. 😢 (I think it works in other parts of the app because we're using different navigation.)

I'll see if I can find something else that works with the latest version of `GoRouter`!

**Comment by hjiangsu** [comment]
Ahh I was looking at this yesterday! I replaced `WillPopScope` with the `BackButtonInterceptor` that we use on other parts of the app. The changes are in this branch: https://github.com/thunder-app/thunder/tree/fix/android-back-button

I haven't created a PR yet because I was still trying to do some tests, but you can check it out and let me know if this works for you!

**Comment by micahmo** [comment]
Oh yeah, that works perfectly, thanks! 😄

**Comment by hjiangsu** [comment]
Awesome, in that case, I'll make a PR for it

**Pull request merged**
