### PR TITLE
Re-organizing settings page and addition of post/comment previews

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR is two-fold. First, it introduces post and comment previews in the settings page. As part of this, I also took the time to reorganize some of the settings around to make it _hopefully_ more intuitive.

Notes:
- The previous Appearance page is moved into it's own page and renamed "Theming"
- I've moved the appearance settings for posts and comments into new pages. To access appearance settings for posts/comments, you will need to navigate from `Settings -> Appearance -> Posts` and `Settings -> Appearance -> Comments` respectively
- For the new post and comment pages, I've added an action which allows the user to reset that page's settings to their defaults
- I've removed the "Score Counters" option from the general settings page as we are deprecating showing user scores on user sidebars (this is a restriction from lemmy starting in 0.19.x, not us)

## Issue Being Fixed

Issue Number: #255

I've linked an related issue here, but the implementation differs from the original issue. I would like to get more feedback on the general feel of the changed settings so feel free to comment on any aspects here.

## Screenshots / Recordings

https://github.com/thunder-app/thunder/assets/30667958/6bddf6f7-d099-42e8-b456-323bcd4c6276

| Comment Appearance | Post Appearance |
|-|-|
|image| image image|

## Checklist

- [ ] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [x] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by hjiangsu** [comment]
@micahmo This should now be ready to go - feel free to take it for a spin and let me know if you think any settings should be moved to a different section!

**Review by micahmo — APPROVED** [review]
Looks great to me! I really like the reorganization and the previews.

Tiny comments:
* I liked that you replaced the ActionButtons for import/export with more standard looking settings items. I wonder if we should do the same for Apply under accessibility profiles and the Delete options under Debug.
* We had talked about having an Advanced section, but with your reorg, I don't think any single page is too overwhelming, so I think we can put this off for now.

**Comment by micahmo** [comment]
One more thing... the post preview isn't working for me. I'll see if it's something obvious!

Uploading qemu-system-x86_64_wBG3xuf5bb.mp4…

**Comment by micahmo** [comment]
Looks like it's because I'm not showing NFSW posts on the feed, so `parsePostViews` is filtering it out and returning an empty list. Hopefully an easy fix!

**Comment by hjiangsu** [comment]
> I wonder if we should do the same for Apply under accessibility profiles and the Delete options under Debug.

I'm not too sure how to apply the same style for accessibility profiles since it's not technically an option, but a confirmation of sorts. We can probably leave this as is for now!

For debug settings, I can definitely make it match better with the rest of the settings!

> Looks like it's because I'm not showing NFSW posts on the feed, so parsePostViews is filtering it out and returning an empty list

Hmm, interesting, I'll take a look at this! It should still return some items as only one of them is marked as NSFW

**Comment by hjiangsu** [comment]
Alright, I've made the changes to debug page and fixed the issues with the post previews not working. Let me know if it all looks good to you now!

**Review by micahmo — APPROVED** [review]
Looks perfect now!

**Pull request merged**
