### PR TITLE
Notification indicator for inbox

### PR DESCRIPTION
**Pull request by kaibagley**
https://github.com/hjiangsu/thunder/issues/233
Hey guys, first pull request ever here

Please review my code, first pull request, first time merging alot of commits, etc. etc...
There's certainly a better way to do this, so please feel free to let me know how to improve this.

Edit: oops, i wanted to merge into `develop`

### CODE REVIEW

**Comment by kaibagley** [comment]
This doesn't work properly, will fix

**Comment by hjiangsu** [comment]
Oh yeah, sorry about that! I forgot to mention to base it off `develop` 😅

**Comment by hjiangsu** [comment]
I think once you're done and the merge conflicts are hopefully resolved, you can @ me and I'll take a look at it when I have time!

**Comment by machinaeZER0** [comment]
Thanks for getting the ball rolling on this @kaibagley!

**Comment by kaibagley** [comment]
Not working properly, will re-draft when I write nicer code

**Pull request closed without merging**
