### PR TITLE
Feature/fab customization

### PR DESCRIPTION
**Pull request by micahmo**
## Pull Request Description

This PR adds support for customizable short-press and long-press actions on both the feed and post FABs.

There are a ton of possible configurations now (my video just demonstrates a few), but I did test as well as I could, despite my demo only showing a few options.

I also think some of the generalization could help us get towards reorderable actions.

This PR also introduces inkwells for settings and the ability to click anywhere on the row to change a toggle.

## Issue Being Fixed

Issue Number: #527 (maybe others)

## Screenshots / Recordings

https://github.com/thunder-app/thunder/assets/7417301/caa99a85-271b-415a-b1bb-e9fbebc33973

## Checklist

- [x] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable? -- No, the settings don't seem to have been converted yet.
- [x] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by hjiangsu** [comment]
I think it looks pretty good overall! Just one point of feedback (that we can do in the future as a separate PR maybe):
- Instead of using the local settings string throughout the code to determine the FAB action, we can create a new enum for FAB actions (FABAction/FabAction or some other name) which would work similarly to SwipeAction enum
  - When setting the setting for the single/long press actions, we would save the name of the FABAction enum name
  - We can then translate the value back from a string (stored in SharePreferences) to a FABAction enum which can then be used everywhere else in the code

You can take a look at how SwipeAction is handled throughout the codebase to get examples! Here is an example of how swipe action is translated from the string to the enum:
```dart
SwipeAction leftPrimaryPostGesture = SwipeAction.values.byName(prefs.getString(LocalSettings.postGestureLeftPrimary.name) ?? SwipeAction.upvote.name);
```

Doing this would then allow us to extend the FAB action enum (e.g., to be able to fetch the associated icon) and keep things a bit cleaner! Anyways, let me know what you think about this. We can still merge this in first and then potentially apply the feedback I mentioned if you'd like!

**Comment by micahmo** [comment]
I agree, that would be an big improvement. Like the `SwipeActions` refactoring I did, it would make things more object-oriented and maintainable going forward. I'll see if I can knock it out.

**Comment by micahmo** [comment]
Alright, I think this is ready to go!

**Comment by hjiangsu** [comment]
Nice! It looks good to me, thanks for adding the improvements!

**Review by hjiangsu — APPROVED** [review]

**Pull request merged**
