### PR TITLE
Fix theming issues with dependency upgrades

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

> Review with whitespace off

This PR fixes some of, if not all, the theming issues mentioned in https://github.com/thunder-app/thunder/pull/1565. I've also upgraded the `flex_color_scheme` package to `8.0.0-dev.2` which contains compatibility with Flutter 3.24.

Notably, the following issues should be fixed:
- bottom nav bar not using shaded colour
- inbox reply cards not using tinted background
- drawer header having coloured background
- search bar background not correct
- account switcher backgrounds not matching bottom sheet

I'm not entirely sure if these issues are fixed (from https://github.com/thunder-app/thunder/pull/1565#issuecomment-2411877790):

> - It looks like the text field hint color is darker (it looks like text that has been typed in, rather than a hint)
> - I think the sizes of the text fields in the login modal are not as tall any more.

Please let me know if you encounter any additional theming issues!

## Issue Being Fixed

Issue Number: N/A

## Checklist

- [ ] If a new package was added, did you ensure it uses an appropriate license and is actively maintained?
- [ ] Did you use localized strings (and added appropriate descriptions) where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Review by micahmo — APPROVED** [review]
All the code changes LGTM! After you merge I'll take a look at the other two issues I found and see if they look any better now. Thanks a ton!!

**Comment by micahmo** [comment]
@hjiangsu Two quick followups on this so far.

* the system navigation bar on Android no longer has the same color app nav bar
* the background color of the instance tagline should be a different color
* the title bar should have a different color once the user scrolls down (this is only broken when the top bar is _not_ pinned)

**Comment by hjiangsu** [comment]
Thanks for mentioning those issues! Would it be possible for you to send some screenshots over of what you mean by them?

**Comment by micahmo** [comment]
> the system navigation bar on Android no longer has the same color app nav bar

Just FYI, I did some looking into this and found some interesting results. It seems like the `SystemUiOverlayStyle` that we're setting is not being respected at all. As a test, I set the nav bar color to purple. You can see in the following screen recording that if I hot reload the app, it respects the color, but as soon as I perform any action, it goes back to (nearly) white. I haven't been able to find any bugs or known breaking changes related to this, though, so I'm not sure what else to do at this point.

https://github.com/user-attachments/assets/59112210-ad56-4986-9a42-d06be47a16a2

I'm wondering if it has something to do with he `flex_color_scheme` upgrade. This issue seems *maybe* related??
https://github.com/rydmike/flex_color_scheme/issues/258

**Comment by hjiangsu** [comment]
Interesting, thanks for looking into that! I'm wondering if there's a theming setting within `flex_color_scheme` that colours the system navigation bar. If so, that could be why it's being overridden when an action is performed.

I can also take a quick look to see if I spot anything regarding this.

**Pull request merged**
