### PR TITLE
Improve settings seearch results

### PR DESCRIPTION
**Pull request by micahmo**
## Pull Request Description

This PR continues to build on the recent settings search feature, and adds the functionality of scrolling to and flashing the selected search result.

I also tested each possible search result and fixed up some things that were missing/wrong.

> Review without whitespace.

## Issue Being Fixed

Issue Number: N/A

## Screenshots / Recordings

https://github.com/thunder-app/thunder/assets/7417301/c7ef228a-23af-463e-a15a-b41356e3fd49

## Checklist

- [ ] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by ggichure** [comment]
Awesome. I reckon Flashing the result twice would enhance the UX.

**Comment by micahmo** [comment]
> I reckon Flashing the result twice would enhance the UX.

I reckon it would too! But I couldn't figure out how to do that with `SmoothHighlight`. Maybe a rebuild after a delay?

**Review by ggichure — APPROVED** [review]

**Comment by hjiangsu** [comment]
Thanks for doing this! Just one point for discussion - I'm noticing that we need to wrap every `ToggleOption` with `SmoothHighlight` for it to work. Could we instead, do that within `ToggleOption`?

This way, when we introduce new settings, it'll make it easier! This is an example of what I mean:

```dart
SmoothHighlight(
  key: settingToHighlight == LocalSettings.reduceAnimations ? settingToHighlightKey : null,
  useInitialHighLight: settingToHighlight == LocalSettings.reduceAnimations,
  enabled: settingToHighlight == LocalSettings.reduceAnimations,
  color: theme.colorScheme.primaryContainer,
  child: Padding(
    padding: const EdgeInsets.fromLTRB(12.0, 0.0, 16.0, 0.0),
    child: ToggleOption(
      description: l10n.reduceAnimations,
      subtitle: l10n.reducesAnimations,
      value: reduceAnimations,
      iconEnabled: Icons.animation,
      iconDisabled: Icons.animation,
      onToggle: (bool value) => setPreferences(LocalSettings.reduceAnimations, value),
    ),
  ),
),
```

Move the implementation for SmoothHighlight into `ToggleOption`. It looks like we might only need to pass in a key:
```dart
ToggleOption(
    highlightKey: settingToHighlight == LocalSettings.reduceAnimations ? settingToHighlightKey : null,
    description: l10n.reduceAnimations,
    subtitle: l10n.reducesAnimations,
    value: reduceAnimations,
    iconEnabled: Icons.animation,
    iconDisabled: Icons.animation,
    onToggle: (bool value) => setPreferences(LocalSettings.reduceAnimations, value),
  ),
),
```

**Comment by micahmo** [comment]
> I'm noticing that we need to wrap every `ToggleOption` with `SmoothHighlight` for it to work. Could we instead, do that within `ToggleOption`?

We could, but it would have to go in the widgets for all the different types of settings, like
* `ToggleOption`
* `ListOption`
* `SettingsListTile`
* Maybe others I'm not thinking of

Any ideas?

**Comment by micahmo** [comment]
Should be all set now!

**Review by ggichure — APPROVED** [review]

**Comment by micahmo** [comment]
If this looks good, any chance we can merge it before any new settings are added? 😆

**Review by ggichure — APPROVED** [review]
LGTM

**Review by hjiangsu — APPROVED** [review]

**Pull request merged**
