### PR TITLE
Fix the keyboard type for the search input

### PR DESCRIPTION
**Pull request by micahmo**
## Pull Request Description

This is a super small fix akin to #687 which fixes the keyboard type for the search field input to prevent some issues with some keyboards.

### CODE REVIEW

**Review by hjiangsu — APPROVED** [review]
LGTM!

**Comment by hjiangsu** [comment]
Just wanted to mention something I noticed - maybe we can change the keyboard type to only be url when we're searching for Posts -> Search by URL?

Otherwise there's no way to add a space when searching for communities or posts!
IMG_1619

**Comment by micahmo** [comment]
Could that be an iOS problem? I can still add a space on Android!

The main reason for this change was that my Android keyboard would add a space after a period (thinking you wanted to start a new sentence), which doesn't work well for URLs. If the iOS keyboard doesn't do that, then maybe this can be an Android/iOS difference rather than a search type difference.

https://github.com/thunder-app/thunder/assets/7417301/1a13321f-5bec-4ec3-aaef-c654b912548a

**Comment by hjiangsu** [comment]
Ahh yeah, it might be platform differences. I'll make a PR to see if I can exclude this behaviour on iOS!

**Pull request merged**
