### PR TITLE
Improved image viewer, part one

### PR DESCRIPTION
**Pull request by CTalvio**
Improves the image viewer a bit

- Move download button to the bottom
- Add share button (basically just copied the code for media share)
- Make background slightly transparent instead of black
- Dismiss now works when tapping/sliding anywhere
- Speed up opening transition

More to be done, but here are these improvements at least, for now.

### CODE REVIEW

**Comment by hjiangsu** [comment]
I'll rebase this to develop and check for any merge conflicts

**Comment by hjiangsu** [comment]
Just curious but was there a specific reason for setting `this.postId = 0`? I'm wondering if its just better to set it to `this.postId` if its not necessary to have the default set to 0

**Comment by CTalvio** [comment]
> Just curious but was there a specific reason for setting `this.postId = 0`? I'm wondering if its just better to set it to `this.postId` if its not necessary to have the default set to 0

I don't recall. I think Android Studio just told me to do that. I am simply trial-and-erroring my way to to having a button for opening the post of an image in the image viewer.

It doesn't work at the moment, so it will have to change. I'm not up to speed on how exactly page transitions work in flutter.

**Comment by CTalvio** [comment]
Going to look at the image viewer some more tonight.

@hjiangsu Anything need changing in this PR aside from the merge conflicts to get these particular improvements merged until I have more figured out?

I'll take a pass the postaId thing at least.

**Comment by CTalvio** [comment]
Will do, and yes. This is basically just #306 but with the stuff that's unfinished commented out, so that we can get these easy additions into users hands asap. #306 will likely take me a while to figure out, as I want to get he tap gestures working, etc.

**Comment by CTalvio** [comment]
This should now be ready to merge, @hjiangsu

**Pull request merged**
