### PR TITLE
Initial ability to view post/comment reports

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR adds the ability to view post/comment reports. If a user is a moderator for a community, or an admin, a new option will show up on the drawer to open a page containing post and comment reports.
- By default, it will show post/comment reports that have not yet been resolved.
- We can perform extra filtering by tapping on the filter icon at the top. This will allow us to show all reports (resolved/unresolved), as well as filter by community.
- The UI/UX is changed slightly from what we're currently using in other places (e.g., user feed page, inbox page, etc.) The goal here was to make it feel more in touch with Material guidelines. As such, the pill shaped options have been replaced with a tab bar for switching between post/comment reports.

This is the first iteration of this, but I have some ideas for additions to this!
- Adding in badge counters to show the number of unresolved reports
- Add the ability to view and resolve private message reports
- Add in quick actions to each report (e.g., to ban offending user, delete/purge offending content, etc)

@micahmo feel free to take a look through the code, but no need to do a deep dive into it as a lot of new files have been added to support reports

@machinaeZER0 it would be great if you could provide any feedback on the overall UI/UX! I feel like I'm fairly happy with it. The only thing bothering me right now is the contents within the filter bottom sheet (it feels a bit awkward but that might just be me)

## Issue Being Fixed

Issue Number: N/A

## Screenshots / Recordings

https://github.com/thunder-app/thunder/assets/30667958/bc6a7fc0-389e-4deb-be19-1fb85bef944f

Adding in some static screenshots to get a better view of the UI

| | |
|-|-|
| simulator_screenshot_CAC3692C-7D91-496F-B4AA-77DA636E67FD | simulator_screenshot_0E750637-5F11-4AB6-B132-0DAFF3E8E8C2|
| simulator_screenshot_9BC04591-235D-4D37-B858-D0BA780A4924 | simulator_screenshot_E945AA35-E391-4D78-ADF8-BFA369B8149B|

## Checklist

- [ ] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Review by micahmo — APPROVED** [review]
Wow, this looks so awesome! I don't really have anything to add to either the code or the UX (without really trying it in-depth myself).

One thing that did come to mind is the filter button. I wonder if we should change the icon slightly when there's a filter applied. The same could be for the modlog.

**Comment by machinaeZER0** [comment]
I think this looks great! And I like your ideas for future additions :) honestly I think my only thought would be to better highlight the reason something is reported - feels like an element that would get a custom color or pill treatment, I think?

**Comment by hjiangsu** [comment]
Thanks for the feedback! I've adjusted it now to make the reason more bolded, and used the error colour to better highlight the reason. Thoughts on this approach?

| | |
|-|-|
|image| image|
|image|image|

**Comment by machinaeZER0** [comment]
I think that's great! Looks very clean :)

**Comment by hjiangsu** [comment]
I'll go ahead and merge this in for the initial feature, and we can continue to add on to this as I mentioned in the original description 😄

**Pull request merged**
