### PR TITLE
Added User Information

### PR DESCRIPTION
**Pull request by bactaholic**
Added new features to user header to display user info

-Custom finals added to calculate Total Score and Account Age in days.
-Added 'i' info button next to username
-Added ModalBottomSheet containing the following user information:
    -Post Count
    -Comment Count
    -Total Count
    -Account Age (days)
    -Post Score
    -Comment Score
    -Total Score
    -Cake Day, formatted yyyy-MM-dd

And the button appears anywhere that the userheader is called, so it can be used in the profile tab to view your own stats, or you can see it on other users pages as well.

https://github.com/thunder-app/thunder/assets/108231591/3e4e4f9d-838c-4fe3-8add-ad3eef161e59

### CODE REVIEW

**Comment by micahmo** [comment]
Is there some overlap here with @CTalvio's new feature?
https://github.com/thunder-app/thunder/assets/7417301/d02f0f16-fbc9-49a2-8f3a-f239cc6c1946

To be honest, I like the little info icon. Takes up much less screen real estate!

**Comment by bactaholic** [comment]
@micahmo @CTalvio 

Crap, didn't know anyone else was working on this sort of thing. @CTalvio's solution has more data on it like bio and block buttons. I like the info button cause its real simple, doesn't take up a lot of space. And I chose to go with the bottomModalSheet because we already use them across the app for everything else like the reply button for posts/comments, create post, and manage accounts.

There are perks to either. I guess its up to @hjiangsu

**Comment by CTalvio** [comment]
My sidebars are already merged, and it looks like out of popular demand, I will be swapping the arrow into an info button.

**Comment by micahmo** [comment]
@bactaholic I definitely like a lot of elements of your implementation. Sorry we didn't see it before the other was merged. You can join us on Matrix to keep up to date. You're also more than welcome to make some improvements based on what's already in.

https://matrix.to/#/#thunderapp:matrix.org

**Comment by bactaholic** [comment]
> My sidebars are already merged, and it looks like out of popular demand, I will be swapping the arrow into an info button. My sidebars also display info such as moderated communities. That user just didn't modoerate any.

Nice. If you want, well i'll let you swap the icon to the info button like you said. I may come through and add some of the stats that I created for my implementation. 
Sorry for the overlap here, I've been away from my coding projects for a little over a week now, didn't see we already had that feature in the latest update.

**Comment by CTalvio** [comment]
Yeah, I did mark myself as assigned in the github issue, but I was a lot more active in the chat, showing off progress. Join us! And well make sure tasks are dealt out evenly. FYI I'm working on a rework for the FABs, I think you added those.

**Pull request closed without merging**
