### PR TITLE
Support accessibility for new gesture picker

### PR DESCRIPTION
**Pull request by micahmo**
Fixing my part of #517.

@shortwavesurfer2009 Maybe you can let me know if these descriptions are good.

### CODE REVIEW

**Comment by shortwavesurfer2009** [comment]
`i think "long "long swipe right", "short swipe right", "short swipe left", and "long swipe left" would be better. So an example would read "short swipe right, downvote" or whatever it was currently set to.

**Comment by micahmo** [comment]
@shortwavesurfer2009 Thanks! Updated as you suggested.

**Comment by shortwavesurfer2009** [comment]
Perfect. I just had a look through the commit and that is perfect

**Comment by hjiangsu** [comment]
LGTM :D

**Pull request merged**
