### PR TITLE
Improve block management

### PR DESCRIPTION
**Pull request by micahmo**
## Pull Request Description

This PR adds a few improvements around block management.

1. Localize account settings page.
2. Show community and user icons in block settings.
3. Show display names.
4. Make users/communities tappable to visit.
5. New ability to add blocks directly from the settings page.
   - Including a new user/community picker dialog with support for autocomplete/search or direct name (via all of the syntax that we support in link detection).

> P.S. I hope the username autocomplete can be used in the post/comment editor at some point (i.e., #256).

## Issue Being Fixed

Issue Number: N/A

### Before

| image |
| - |

### After

https://github.com/thunder-app/thunder/assets/7417301/d3b7cbf6-d8d1-4e48-aa7e-861f89e83a93

## Checklist

- [ ] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [x] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by machinaeZER0** [comment]
Beautiful!

**Comment by hjiangsu** [comment]
Looks pretty nice! Just a couple of suggestions:
- Could we move the logic for the user/community autocomplete to their own separate widgets as a way for them to be re-used elsewhere in the future? This could be placed in the `lib/shared` directory!
- Not sure if its just me, but I feel like theres a bit too much padding on the right side of the screen (where the add/remove icons are) Maybe we can reduce the padding there slightly?

**Comment by micahmo** [comment]
> Could we move the logic for the user/community autocomplete to their own separate widgets as a way for them to be re-used elsewhere in the future? This could be placed in the `lib/shared` directory!

Done!

> I feel like theres a bit too much padding on the right side of the screen (where the add/remove icons are)

I agree! This seems to be a function of the `ListTile`'s default `contentPadding`. I overrode that, and I think it's better now.

| image |
| - |

**Review by hjiangsu — APPROVED** [review]

**Comment by hjiangsu** [comment]
Looks good now! Thanks :D

**Pull request merged**
