### PR TITLE
Feature/post share sheet

### PR DESCRIPTION
**Pull request by micahmo**
This PR aims to bring extended share functionality within the post view. Currently pressing share will only share the link to the post. Now it can also share the external link and/or media as applicable.

I also reordered the main share modal so that the two community actions were adjacent.

### Demo

https://github.com/thunder-app/thunder/assets/7417301/23267151-c9d8-4ea1-8f65-30936bf1db93

### CODE REVIEW

**Comment by machinaeZER0** [comment]
This looks good! Not sure if it has something to do with your settings, but it looks like the share icon is darker than the other icons in post view? On the latest apk I'm not seeing that same coloring issue, so just clarifying!

**Comment by hjiangsu** [comment]
> This looks good! Not sure if it has something to do with your settings, but it looks like the share icon is darker than the other icons in post view? On the latest apk I'm not seeing that same coloring issue, so just clarifying!

I think that's most likely because @micahmo isn't logged in. If you are not logged in, then those actions will be disabled by default so you can't accidentally press on them!

**Comment by hjiangsu** [comment]
@micahmo Would you like to log this change somewhere into the `changelog.md` file as well? That'll help me with having to do it after the fact  😅

**Comment by micahmo** [comment]
@machinaeZER0 Yes, I wasn't logged in, sorry! 😆

> Would you like to log this change

@hjiangsu Sure! Do you want contributors to get in the habit of doing that?

**Comment by hjiangsu** [comment]
> Sure! Do you want contributors to get in the habit of doing that?

Yes please! I'll maybe add that into the README as well. It's just harder for me to keep track of all the PRs merged and which ones were already included in the changelog 😅

**Comment by machinaeZER0** [comment]
Ahh, my bad! That makes total sense, sorry 😂

**Comment by micahmo** [comment]
> I'll maybe add that into the README as well.

Would you like to consider adding a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)? You can add a checklist, and GitHub will detect these as tasks. You can prevent PRs from being merged whose tasks are not complete.

**Comment by hjiangsu** [comment]
That might be useful! I'll have a look at it

**Comment by micahmo** [comment]
All set!

**Pull request merged**
