### PR TITLE
Improved image viewer, part two

### PR DESCRIPTION
**Pull request by CTalvio**
There will likely be a part three.

I've figured out how to show the download info snackbar without duplication, as well as how to do this:

[Kazam_screencast_00000.webm](https://github.com/thunder-app/thunder/assets/4365015/a4e470af-00c5-4bf5-ba33-4c343d1ae3f7)

### CODE REVIEW

**Comment by CTalvio** [comment]
@hjiangsu

Something's up with the BlocProvider, I get the following error trying to open the post from the image viewer: `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Error: Could not find the correct Provider<AccountBloc> above this ImageViewer Widget`

**Comment by micahmo** [comment]
This looks great!!

**Comment by CTalvio** [comment]
> This looks great!!

Swiping images away is so satisfying now...

I think I found the example code I need to implement double tap zoom, but onDoubleTap somehow won't accept the exact function ExtendedImage's docs tell you to use for that.

**Comment by CTalvio** [comment]
@hjiangsu gonna work on other things again, you can merge this for now.

Also if you want to take a look at the comment button, you'll probably figure it out faster than me.

**Comment by hjiangsu** [comment]
Sounds good! I'll take a look at it when I have the chance! For now, I'll merge this in :D

**Pull request merged**
