### PR TITLE
Ability to navigate to the previous page with full screen swipe gesture

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

Adds ability to navigate to the previous page with full screen swipe gesture. This also changes WillPopScope with `BackButtonInterceptor` to close FAB actions. Check the changes with whitespace turned off

This is the current behaviour:
- If you are on a feed type page (community feed/user page) and LTR swipe gestures are active, you can swipe to go back from the edge of the screen
- If you are on a feed type page (community feed/user page) and LTR swipe gestures are NOT active, you can do a full screen swipe to go back

- If you are on a post type page and LTR swipe gestures are active, you can swipe to go back from the edge of the screen
- If you are on a post type page and LTR swipe gestures are NOT active, you can do a full screen swipe to go back

There are still some more things to be done:
- Check that FAB actions close when swiping back
- Double check compatibility with LTR swipe actions
- Potentially add in a setting to disable (although, the more I look at it, the less I feel like we need this)

## Issue Being Fixed

Issue Number: #198, #302, #312 

## Checklist

- [ ] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by hjiangsu** [comment]
@micahmo you can take a brief look at this and let me know how it feels on Android!

**Comment by micahmo** [comment]
Looks like a great start! I think this is definitely the way forward. Unfortunately there are quite a few quirks now. I think we will need to iterate back and forth until things work as expected on both Android and iOS. 😊

* Pressing the back button doesn't navigate back from a post any more.

https://github.com/thunder-app/thunder/assets/7417301/0b226973-7675-44bf-99ab-731f1521bf20

* From a post, pressing the back button closes the FAB. From the main feed, pressing the back button closes the FAB but also triggers the first of two back presses to exit.

https://github.com/thunder-app/thunder/assets/7417301/21bbf642-a08e-44b4-b0c2-567d89cc78ff

* Pressing the UI back button does not close the FAB.

https://github.com/thunder-app/thunder/assets/7417301/4feb47ec-0fc0-4665-880d-6c31519eef02

* When I don't disable swipe gestures, pressing the back button triggers the `Hero` animation, which I think looks funny now. Maybe we should abandon it? (It already doesn't work for the image popup.)

https://github.com/thunder-app/thunder/assets/7417301/5dd94259-8175-4000-a660-29c231ea2cf7

* When I do disable swipe gestures, I can only swipe back on the post body, not the comments.

https://github.com/thunder-app/thunder/assets/7417301/45e4aa0e-8208-454b-bf00-1e387fe8e4a1

**Comment by hjiangsu** [comment]
> Pressing the back button doesn't navigate back from a post any more.

This could be due to the BackButtonInterceptor? I'll try to look more into that

> From a post, pressing the back button closes the FAB. From the main feed, pressing the back button closes the FAB but also triggers the first of two back presses to exit.

This is also possibly due to BackButtonInterceptor

> Pressing the UI back button does not close the FAB.

This is also happening to me, I have a brief idea on how to potentially solve this

> When I don't disable swipe gestures, pressing the back button triggers the Hero animation, which I think looks funny now. Maybe we should abandon it? (It already doesn't work for the image popup.)

We can have further discussions on this!

> When I do disable swipe gestures, I can only swipe back on the post body, not the comments.

This is a weird one, I thought it was working but I'll double check. Just double checking but you only disabled the comment swipe gestures, but kept the actions enabled? Or did you disable both the actions and the comment swipe gestures?

**Comment by micahmo** [comment]
> Just double checking but you only disabled the comment swipe gestures, but kept the actions enabled?

I should clarify that I only disabled the LTR gestures. It would be nice if we could detect it at that granularity so that I don't also lose RTL!

**Comment by hjiangsu** [comment]
> Pressing the back button doesn't navigate back from a post any more.

@micahmo I just pushed a change to hopefully fix this - could you double check?

**Comment by hjiangsu** [comment]
> I should clarify that I only disabled the LTR gestures. It would be nice if we could detect it at that granularity so that I don't also lose RTL!

It should already hopefully detect those differences - if you disable LTR actions, full page swipe should still work even with RTL swipe actions!

**Comment by micahmo** [comment]
> I just pushed a change to hopefully fix this - could you double check?

Yep, this is good now! (Still doesn't dismiss the FAB.)

> I just pushed a change to hopefully fix this - could you double check?

Sure thing!

https://github.com/thunder-app/thunder/assets/7417301/669b223f-443a-4b05-aa97-8b1c3394e581

**Comment by hjiangsu** [comment]
@micahmo I pushed another change to handle the back button on post not dismissing the FAB

**Comment by micahmo** [comment]
> I pushed another change to handle the back button on post not dismissing the FAB

Nice! Both the OS and UI back buttons dismiss the FAB and navigate back to the main feed from a post. 👏

**Comment by hjiangsu** [comment]
> When I do disable swipe gestures, I can only swipe back on the post body, not the comments.

Man, this one is going to be a bit harder to figure out. It seems like there is a difference in how iOS/Android treats this - iOS seems to work but not Android

**Comment by micahmo** [comment]
> Man, this one is going to be a bit harder to figure out. It seems like there is a difference in how iOS/Android treats this - iOS seems to work but not Android

Ahh, that's too bad. 😔 @ajsosa or I might have to look at some point.

**Comment by hjiangsu** [comment]
@micahmo When you have the chance, could you do another check for all the previous cases you've had? I got the LTR full screen swipe working on the post page, but not the feed page yet

**Comment by hjiangsu** [comment]
Added the ability to use full page swipe to go back when on feed pages. Theres some caveats here though:
- When viewing a community, the swipe gesture to open the community sidebar is no longer working
- There was a swipe gesture detector on each post card to open the feed drawer, this has been removed for now

@micahmo Can you test out everything else again and see if it works as expected? I'll see if there are alternatives to opening the community drawer/subscriptions drawer after!

**Comment by micahmo** [comment]
@hjiangsu This is working great! I would say it's mergeable as is. I made the following notes but they can be discussed later.

> I'll see if there are alternatives to opening the community drawer/subscriptions drawer after!

This would be nice and would complete #198 for me. 😊

* Pressing back on the main feed still both closes the FAB and triggers an exit. I think it should do one or the other.

* The `Hero` animation is still inconsistent. It only happens when comment gesutres are on (and thus swipe back is off). I also found a case where it looks even more funny (when the image is off screen).

https://github.com/thunder-app/thunder/assets/7417301/f7093e71-8702-4e14-8845-de7490010660

* I was wondering, if RTL gestures are on, could swipe back still work on post body? Just a thought.

Nice work!

**Comment by hjiangsu** [comment]
> Pressing back on the main feed still both closes the FAB and triggers an exit. I think it should do one or the other.

I can take a brief look at this!

> The Hero animation is still inconsistent. It only happens when comment gesutres are on (and thus swipe back is off). I also found a case where it looks even more funny (when the image is off screen).

This can maybe be done in a different PR since its not related to the issue!

**Comment by hjiangsu** [comment]
> Pressing back on the main feed still both closes the FAB and triggers an exit. I think it should do one or the other.

Alright, this should be done! Feel free to do another walkthrough of all the use-cases to double check everything! @micahmo If it all seems good, then this should be ready to be merged in

**Comment by micahmo** [comment]
Looks good!! 🎉

**Review by micahmo — APPROVED** [review]

**Pull request merged**
