### PR TITLE
Initial moderator post actions (lock, pin, remove)

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This is a PR which introduces moderator actions to the post actions bottom sheet. Currently, it includes **locking, pinning, and removing posts**.

~~This is still in draft since there are a couple of things that still need to be addressed.~~
- [x] Set up a way to dynamically change the text of the action (from lock post to unlock post)
- [x] Clean up localizations and changes

## Issue Being Fixed

Issue Number: Partially solves https://github.com/thunder-app/thunder/issues/1007

## Screenshots / Recordings

Update (added trailing icon to moderator option)
Simulator Screenshot - iPhone 15 Pro - 2024-02-08 at 11 24 54

https://github.com/thunder-app/thunder/assets/30667958/2e6446c4-0032-4e57-87cf-fe9b56436c9b

## Checklist

- [ ] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by micahmo** [comment]
I know this isn't ready for review yet, but I just wanted to comment that I like the overflow menu for moderator actions! I've been wanting to add some new actions to the long-press menus as well, as had been thinking about how to reorganize it. I'm thinking, for example, community, user, and instance actions can all overflow rather than having two entries each.

Should there be an arrow on the right-hand side like the "Top" sort menu item?

**Comment by hjiangsu** [comment]
This is now ready for review! I've updated the body of the PR to include screenshots and a video

**Review by micahmo — APPROVED** [review]
Wow, this is so awesome!

The only usability question I had was about the "Reason" prompt. I do know we have a similar prompt for reporting comments, but it uses a modal. I was wondering if either that mechanism should use this dialog or vice versa. I was also wondering if the text input should be bigger by default? Or maybe a better question would be to ask what happens when you enter a lot of text? Does it grow vertically or overflow horizontally?

**Comment by hjiangsu** [comment]
> The only usability question I had was about the "Reason" prompt. I do know we have a similar prompt for reporting comments, but it uses a modal.

Ahh good catch! I forgot that the report comment used a modal rather than dialog. I can try to adjust the logic on my end to do something similar to the comment reporting!

**Comment by hjiangsu** [comment]
I created a new widget to hold the inline text-input. Right now, it'll be used for the mod removal but we can extend that to post report and comment report in the future!

One caveat with this right now is that cancelling the action closes the modals (does not bring you back to the options)

I also adjusted it a bit to match more with the current bottom sheet modal. Thoughts?

https://github.com/thunder-app/thunder/assets/30667958/9de2724d-5944-4270-8852-f6cc59a5fcf9

**Comment by micahmo** [comment]
Looks great! Nice to immediately focus the keyboard as well!

**Comment by hjiangsu** [comment]
If this is good, I'll go ahead and merge this in?

**Comment by micahmo** [comment]
Go for it!

**Pull request merged**
