### PR TITLE
Chore: Upgrade dependencies for Flutter 3.24 compatibility

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR updates Thunder to be compatible with Flutter 3.24. I've upgraded all the packages to their latest versions (using `flutter pub upgrade --major-versions`)

Note: The package `flex_color_scheme` has not been updated yet as the next version is still a WIP. However, I opted to continue with the upgrade regardless to reduce potential tech debt from upgrading between multiple major Flutter versions (e.g., 3.22, 3.24, etc.)

Due to this, there may be some visual bugs associated with the upgrade. I'll see if there are any simple workarounds for these issues in future PRs.

@micahmo I've tested the build on Android and it looks to be building properly, but let me know if you encounter any issues! I'll be closing this PR (https://github.com/thunder-app/thunder/pull/1372) as this one supersedes it

## Issue Being Fixed

Issue Number: N/A

## Checklist

- [ ] If a new package was added, did you ensure it uses an appropriate license and is actively maintained?
- [ ] Did you use localized strings (and added appropriate descriptions) where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Review by micahmo — APPROVED** [review]
LGTM! Feel free to merge this now and I'll let you know if I run into any issues as I daily drive it.

**Comment by micahmo** [comment]
> The package `flex_color_scheme` has not been updated yet as the next version is still a WIP. However, I opted to continue with the upgrade regardless to reduce potential tech debt from upgrading between multiple major Flutter versions (e.g., 3.22, 3.24, etc.)
> 
> Due to this, there may be some visual bugs associated with the upgrade.

Hey @hjiangsu I believe I've seen at least two issues related to color after the upgrade. Note that I don't have an old version to test against, so this is just from memory (although I'm sure we could dig up screenshots from other PRs).

### I believe the bottom nav bar should have a shaded color and not blend into the background of the posts.

| image |
| - |

### I believe each of the reply cards is supposed to have a tinted background.

| image |
| - |

**Comment by hjiangsu** [comment]
Thanks for noting these down! I'll also note down a few things I've noticed:

> Drawer header should not have a coloured background

simulator_screenshot_D28CB16B-D024-434F-89F2-6A51F800C50F

> Search bar should have a coloured background

simulator_screenshot_64C6892C-4F0E-4626-9D2F-807FF66FF764

**Comment by micahmo** [comment]
A couple more things to add onto this!

* It looks like the text field hint color is darker (it looks like text that has been typed in, rather than a hint)
* I think the sizes of the text fields in the login modal are not as tall any more.

**Comment by hjiangsu** [comment]
It looks like `flex_color_scheme` released a pre-release dev version with compatibility for Flutter 3.22. I tried it out for a bit and it seems to fix some of the issues that were mentioned here (but introduced some other visual issues)

Feel free to try it out if you'd like and let me know if there are any other issues noted. I'm mainly waiting for  `flex_color_scheme` to be updated (and fix most/all of the visual issues if needed) before releasing a new pre-release version for Thunder

To use the latest pre-release, set `flex_color_scheme` to be `^8.0.0-dev.1`: https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/install

**Pull request merged**
