### PR TITLE
A couple small FAB improvements

### PR DESCRIPTION
**Pull request by micahmo**
## Pull Request Description

This PR contains a couple of minor visual fixes to the FAB.

1. Restore the opening animation that I broke.
2. Redesign the extended options in combined mode. This should look more like the quick actions from an Android launcher, for example.

> Review without whitespace.

## Issue Being Fixed

Issue Number: N/A

### Before and After for number 1

https://github.com/thunder-app/thunder/assets/7417301/25b3816d-3ccd-4dc6-8580-b87d41943409

https://github.com/thunder-app/thunder/assets/7417301/b914ec22-930e-47c4-ae1c-20355c470745

### Before and After for number 2

| image |
| - |

https://github.com/thunder-app/thunder/assets/7417301/c19641e1-e189-438c-840a-08bb25eeb5d0

## Checklist

- [ ] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by machinaeZER0** [comment]
I like the new styling for 2! I do wonder if we should consider adding a little more padding to each option to ensure the popup options are easily tappable?

**Comment by micahmo** [comment]
> I do wonder if we should consider adding a little more padding to each option to ensure the popup options are easily tappable?

How does this look?

|  image|
| - |

**Comment by hjiangsu** [comment]
Do you have a screenshot of the Android launcher quick gestures for reference? I think maybe adding some side padding (left/right) would also look a bit better!

Also, another point for discussion, should the icon be on the left or right? I think most of the icons right now are on the left but let me know your opinions!

**Comment by hjiangsu** [comment]
I think thats much better! Thoughts @machinaeZER0?

**Comment by machinaeZER0** [comment]
I like it!

**Comment by machinaeZER0** [comment]
Oh - how does it look in dark/black mode?

**Comment by micahmo** [comment]
image

**Review by hjiangsu — APPROVED** [review]

**Comment by hjiangsu** [comment]
I'll go ahead and merge this is as I think it looks good! If there are any further changes, we can add that in with a new PR

**Comment by machinaeZER0** [comment]
Yay! Will there be a new nightly soon? I'm excited to see all the improvements since the last one in action :)

**Comment by hjiangsu** [comment]
@machinaeZER0  Yup, expect one to be released either today or tomorrow!

**Comment by machinaeZER0** [comment]
Yessssss

**Comment by micahmo** [comment]
@hjiangsu Oops, I didn't commit the changes from the last screenshot as I was waiting for feedback, sorry! I'll open a new PR.

**Pull request merged**
