### PR TITLE
Optionally show text post indicator

### PR DESCRIPTION
**Pull request by micahmo**
As discussed in #370, this PR brings back the option (off by default) to show a placeholder icon for text-only posts (to bring them into uniformity with media and link posts).

https://github.com/thunder-app/thunder/assets/7417301/34b23301-8bc0-4d8c-bf0e-71fee310ce80

### CODE REVIEW

**Comment by machinaeZER0** [comment]
Yay!

**Comment by machinaeZER0** [comment]
It's been gone so long I've forgotten (lol) - did tapping the indicator work like other posts, where it let you view content without marking it as read?

**Comment by micahmo** [comment]
> did tapping the indicator work like other posts, where it let you view content without marking it as read?

No, I'm afraid not. It just opens the full post. Since there's no media or link to open, it just opens the full post, which always mark it as read (current). Is this something you'd want?

**Comment by machinaeZER0** [comment]
Just curious! Couldn't remember the original functionality :) I could see a case being made for it but I don't feel strongly about it

**Comment by hjiangsu** [comment]
I have merged in #384 so you can adjust the border radius value and we should be good to go!

**Comment by micahmo** [comment]
All set, thank you!

**Pull request merged**
