### PR TITLE
Platform specific font scaling and more font scaling options

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

Creates a way for font sizes to be scaled according to the platform. This is because it seems like there are differences in the way fonts are scaled between iOS and Android

This also adds in two new font scaling options for more granularity:
- Comment font scaling
- Metadata font scaling

The different font scalings are applied closely to match #510's description

It would be good for anyone on Android to test out the changes to see if the font scaling sizes are appropriate!

## Issue Being Fixed

Issue Number: #301, #510

## Screenshots / Recordings
simulator_screenshot_40D6A831-B0BA-4D28-9D9F-4BEB40E29244

N/A

## Checklist

- [x] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [x] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Review by micahmo — APPROVED** [review]
@hjiangsu I'd like to test this on Android (which will be later today) if that's ok, but otherwise approved!

**Comment by hjiangsu** [comment]
@micahmo I've added a bit more to this PR 😅 - thought the two issues were somewhat linked so decided to do them together

**Comment by machinaeZER0** [comment]
Sorry, I still don't have a test environment set up - would you clarify if the new defaults will still look basically the same as they do now? It looks at a glance like the font size is consistent in a given post, just that the title is bolded. Is that correct?

As an aside, one thing I'm so thankful for in Thunder (a pet peeve with some other apps) is that oftentimes adjusting the font size in an app doesn't tweak line spacing appropriately to accommodate, which often means bigger or smaller text will look weirdly cramped or floating in a sea of empty space. I feel like Thunder really nails font spacing/content padding in a lovely way, and I really appreciate that!

**Comment by hjiangsu** [comment]
>  would you clarify if the new defaults will still look basically the same as they do now (albeit slightly larger overall on Android)?

Yeah, I think everything should look almost the same, although it'll be ever so slightly larger on Android (1.0 scale vs 0.95 from before) Most of the changes should happen on the iOS side of things, where everything will be slightly smaller!

I'll definitely add this as part of a pre-release for people to test out and see if the scaling should be adjusted more!

**Comment by micahmo** [comment]
Hmm, the text is quite a bit larger on Android now. I mean, not to a crazy extent, but having gotten used to the size it was before, I'm not sure I like this. 😅

https://github.com/thunder-app/thunder/assets/7417301/bb0418fa-ca39-4770-8dfe-599bfaad6533

https://github.com/thunder-app/thunder/assets/7417301/802e2b24-6d88-4f73-96da-0a97df169f06

**Comment by machinaeZER0** [comment]
I don't mind it from what I'm seeing, but it is noticeably different for sure (took a while for me to get used to it being smaller, which is why I filed the ticket all those weeks ago). 

I wouldn't want to get toooo granular (especially if it's a pain to code), but instead of having a couple of sizes to choose from, we could let people choose a multiplier value on a slider or something? Then people who are used to .95 would be able to choose it (where I feel like the next smallest size would be a larger jump than that in the current setup). 

Do you think it's something you could get used to, potentially? It should be pulling the base size from your phone settings...

**Comment by hjiangsu** [comment]
Dang, I wonder if we can get an older build to compare with from before the text scaling was added in.

I could just revert the text scale down to the same value as before and that should solve the issue again 😅

**Comment by micahmo** [comment]
> I could just revert the text scale down to the same value as before

I think that would satisfy those who have gotten used to the sizing of things in Thunder. Honestly the sizing being so nice out of the box is one of the things that immediately grabbed me about Thunder. Liftoff is too big, Sync is too small, etc. Obviously we'll have customizations for fine-grained control, but I like the previous values as the defaults. (Just my opinion.)

**Comment by machinaeZER0** [comment]
I still have screenshots from when it changed initially, but really what you're seeing now should effectively match what it was back then:





At this point I've definitely gotten used to .95 on android, and I don't know that anyone's really complained since adding in size options (beyond maybe wanting more of them, which this is already addressing). If Micah likes .95 I'm personally more than happy if it stays that way :) just my two cents!

**Comment by micahmo** [comment]
@hjiangsu Yep, looks perfect to me now! Thanks for that! I guess these kinds of tweaks are fine now that they're platform-specific. 😊

**Pull request merged**
