### PR TITLE
User avatar support for comments and post views

### PR DESCRIPTION
**Pull request by iparks99**
## Pull Request Description

Added toggle options to Settings -> Appearance -> Comments -> Show User Avatar and to Settings -> Appearance -> Posts -> Post Body Settings -> Show User Avatar.

If these settings are toggled on, then when a user views a post, the poster and commenters will have their avatars appear to the left of their display names.

## Issue Being Fixed

Enhancement to display user avatars in post view.

Issue Number: #1221, #600

## Screenshots / Recordings

image
image
Screenshot from 2024-04-12 16-04-25

## Checklist

- [ ] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by iparks99** [comment]
@micahmo is there a better way to get the user avatars than I did here? Perhaps it's unfounded, but I'm worried I would be excessively straining the instance by pulling so many user avatars for bigger comment trees. Is it possible to fetch smaller sized avatar files from the instance?

**Comment by hjiangsu** [comment]
Thanks for taking on this!

> Is it possible to fetch smaller sized avatar files from the instance?

There is a way to query for a resized image, given that the image is hosted on the instance. To do so, I believe you have to append a query string at the end of the URL. For example:

```
https://sopuli.xyz/pictrs/image/cd319103-2136-48d5-a326-fb0afed527b0.png?thumbnail=256&format=png
```



In this case, the relevant parameters are `thumbnail=512&format=webp`
- `256` corresponds to the re-sized width/height in pixels. I'm not entirely sure if it corresponds to the width, or the height so we might have to test that out.
- `format=png` corresponds to the format of the image that we want to get back. This parameter isn't necessary, but its useful if we want to enforce a specific file type

More information about this is present in https://github.com/thunder-app/thunder/issues/675. Aside from that, `UserAvatar` uses `CachedNetworkImage` which should help reduce requests if we're requesting the same images!

---

For this to work, I'd imagine that we would have to do the following:
- Add a parameter to `UserAvatar` indicating the size of the image/thumbnail. This parameter should be nullable so that we can retrieve the full size image if necessary
- If that parameter is passed in, check to see if the URL is a `pictrs/image` endpoint. This might be as simple as checking if the URL contains `/pictrs/image/`

**Comment by iparks99** [comment]
Thanks for the detailed info @hjiangsu! I've added two optional parameters to `UserAvatar`: `int? thumbnailSize` and `String? format`. The code block I added only adds these parameters to the query if they are present and the avatar URI contains `/pictrs/image/`. I tested some of the URIs it output and they're definitely thumbnail sized :)

**Review by micahmo — APPROVED** [review]
Hey, sorry for taking so long to get back to this! I just wanted to say that this is an awesome implementation. The only super minor UI feedback I have is that there seems to be a bit of space to the left of the avatar. This is especially obvious when it's a "special" user, or when you see the inkwell. Maybe that could be shrunk down to about the same amount as between the avatar and the text.

| image |
| - |

P.S. I would love to see this implementation optionally extended to a few other places, like...
* community name in post body
* user and communities names in feed in both Card and Compact modes
	* Note that we already have Theming > Posts > Show Community Icons for Card View, but I think your implementation (smaller icons, and integrated with the name chip) is even better. :blush:

**Comment by iparks99** [comment]
How do we feel about me baking the avatars into the full name widgets then? That way the avatars show up wherever the usernames or community names appear.

The full name widgets could return a row with two children: an optional (user/community) avatar, and the textspan it currently returns. The full name widgets could then either take in an optional avatar parameter, or just the community and grab all the requisite fields from that object.

Then we could have two global toggleable settings: show user avatars and show community icons.

e.g. both widgets in `full_name_widgets.dart` would return something like:
```dart
return Row(
  mainAxisSize: MainAxisSize.min,
  crossAxisAlignment: CrossAxisAlignment.center,
  children: [
    if (avatar != null)
      Padding(
        padding: const EdgeInsets.only(right: 3.0),
        child: avatar,
      ),
    autoSize
        ? AutoSizeText.rich(
            softWrap: false,
            maxLines: 1,
            overflow: TextOverflow.fade,
            style: textStyle,
            textSpan,
          )
        : Text.rich(
            softWrap: false,
            overflow: TextOverflow.fade,
            style: textStyle,
            textScaler: TextScaler.noScaling,
            textSpan,
          )
  ],
);
```

Thoughts @micahmo?

**Comment by micahmo** [comment]
> How do we feel about me baking the avatars into the full name widgets then?

I think that makes a lot of sense! We just have to make sure either (a) the avatars look good everywhere the full name widget is used, or (b) there's an option to hide it (even when the setting is enabled).

**Comment by hjiangsu** [comment]
> How do we feel about me baking the avatars into the full name widgets then? That way the avatars show up wherever the usernames or community names appear.

I think this is a good idea! Although, I would like to make a slight tweak here - we can place the user avatars within `UserChip` rather than the full name widgets. For reference, UserChip was recently added in https://github.com/thunder-app/thunder/pull/1281

This should alleviate the concern that @micahmo had since the UserChip only shows up in PostView and CommentHeader at the moment!
> the avatars look good everywhere the full name widget is used

**Comment by iparks99** [comment]
Sounds good! I think I'll just close this PR and open a new one.

**Pull request closed without merging**
