### PR TITLE
Fix double back

### PR DESCRIPTION
**Pull request by micahmo**
This is an attempt to fix an issue discovered by @machinaeZER0 and demonstrated [here](https://github.com/thunder-app/thunder/pull/338#issuecomment-1636641301). (There are also some formatting changes introduced by workspace settings.)

Please [review without whitespace](https://github.com/thunder-app/thunder/pull/374/files?diff=split&w=1).

### CODE REVIEW

**Comment by hjiangsu** [comment]
Looks good!

**Comment by machinaeZER0** [comment]
Thanks for helping me troubleshoot! What a speedy fix!

**Comment by micahmo** [comment]
@machinaeZER0 Of course, let me know if it actually works! 😆

**Comment by machinaeZER0** [comment]
I haven't been able to reproduce since upgrading to the latest apk, so things are looking good! 😄

**Pull request merged**
