### PR TITLE
Migrate from old BottomNavigationBar to NavigationBar

### PR DESCRIPTION
**Pull request by ggichure**
## Pull Request Description

This PR migrates from old `BottomNavigationBar` to `NavigationBar`
## Issue Being Fixed

Issue Number:  #764

## Screenshots / Recordings
Screenshot_1695980373

## Checklist

- [x] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by ggichure** [comment]
> Hey @ggichure, thanks for the PR!
> 
> Unfortunately, with some of the refactor that has been taking place surrounding the feed page, the bottom nav bar code was moved elsewhere. The bottom nav bar code is now in `lib/thunder/widgets/bottom_nav_bar`. It would be appreciated if you could make the changes to the new file if its not too much work 😅

Will do and submit a PR by EOD tomorrow.

**Comment by hjiangsu** [comment]
Thanks, I appreciate it! Sorry again for this 😅

**Comment by ggichure** [comment]
@hjiangsu I force pushed when rebasing and it closed the PR. Please reopen it, else I can create a new PR.

**Comment by hjiangsu** [comment]
Reopened! Let me know if its all good on your end

**Comment by ggichure** [comment]
Screenshot 2023-10-03 at 22 52 36


> Reopened! Let me know if its all good on your end


All good. Ready for review.

**Comment by hjiangsu** [comment]
So I'm just running the latest develop build (with this change) and I'm finding the animations a bit weird when navigating through many pages at once (e.g., navigating from feed page to settings page).

I wonder if we can potentially fix that. I'm assuming this is because we still have the option of animating through pages, which is what is triggering this issue.

https://github.com/thunder-app/thunder/assets/30667958/822e90e7-b02b-46ee-aef7-3053f4a5a4ab

**Comment by ggichure** [comment]
> So I'm just running the latest develop build (with this change) and I'm finding the animations a bit weird when navigating through many pages at once (e.g., navigating from feed page to settings page).
> 
> I wonder if we can potentially fix that. I'm assuming this is because we still have the option of animating through pages, which is what is triggering this issue.
> RPReplay_Final1696435771.mp4

I'll have a look.

**Comment by micahmo** [comment]
@hjiangsu Are you talking about how all of the icons are highlighted at the bottom while it scrolls through the pages? Technically the old nav bar did that as well, but since the highlight wasn't as prominent, it wasn't as noticeable.

This goes back to the discussion we had in Matrix about whether we should really be scrolling through all the pages like that. It is kind of cool, but I think it's also in the minority of apps that do something like that. 😊

**Pull request merged**
