### PR TITLE
Tweaks to comment images and buttons

### PR DESCRIPTION
**Pull request by CTalvio**
Limits vertical and horizontal size of images in comments. The padding, height, and width of the comment actions have also been tweaked. The lack of top padding can look quite goofy.

Button height reduced, while width is increased, maintaining a reasonable tap target size while taking up ever so slightly less vertical space.

Screenshot_20230720_032549

Above is current appearance, below is the tweaks this PR applies.

Screenshot_20230720_032520

### CODE REVIEW

**Comment by CTalvio** [comment]
#366

**Comment by machinaeZER0** [comment]
This is a huge improvement! Defer to you, but should we indicate in some way that an image is cropped/tapping it will show the full image? Do we currently do that anywhere else in a way we could replicate here?

**Comment by micahmo** [comment]
> should we indicate in some way that an image is cropped/tapping it will show the full image?

I don't know what this would look like UI/UX-wise, but I agree. This get me in Telegram sometimes (where it's unpredictable whether images are cropped or not). You might just think that's the whole thing.

**Comment by machinaeZER0** [comment]
Maybe some sort of linear gradient overlay coming up from the bottom? Probably wouldn't have to be too dark. I think the rounded corners already present do help as well with suggesting that this is a thumbnail, so this would just be a little extra touch to make it (hopefully) obvious

**Comment by CTalvio** [comment]
I wont be adding any further thumbnailing is this PR, moving onto FABs. @hjiangsu feel free to merge

**Comment by hjiangsu** [comment]
Looks good!

**Comment by CTalvio** [comment]
Realised a bonus feature. Comments that are just an image, have almost no area to tap to collapse them.

This fixes that.

**Pull request merged**
