### PR TITLE
Refactor post metadata and user/community chips

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR refactors the post view's metadata (comment count + date/time), and the post view username/community information.
- Removes the old `PostCardMetaData` widget
- Refactors `PostViewMetaData` to use the same widgets as the post card (for comment count, date/time)
- Refactored the logic for determining special users and colours.
- New widgets have been created for user/community chips which apply special colours and icons (similar to how comment header and post page show a user's special status)
- Fixed an issue where the full name widgets were not applying the proper instance colour - separate PR for this #1282 

## Issue Being Fixed

Issue Number: N/A

## Checklist

- [ ] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by hjiangsu** [comment]
@micahmo I believe this should be good to go now if you want to take a look at it!

**Review by micahmo — APPROVED** [review]
I haven't tested but the code LGTM! Seems like a very nice refactoring! 😊

**Comment by hjiangsu** [comment]
Sounds good! I'll go ahead and merge this in (unfortunately, it might cause some merge conflicts on some other PRs but I'm hoping its not too much of a hassle 😅)

**Comment by micahmo** [comment]
Yes I think this will at least affect @iparks99 in #1300. But maybe the avatar could be made part of the `UserChip`?

**Pull request merged**
