### PR TITLE
Customizable Post Card Metadata

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This draft PR adds the ability to customize the post card metadata. Currently, it handles the compact mode, but work is being done to implement it for the card view.

There's a few new things implemented here:
- The `PostCardMetadata` widget was completely refactored to handle this new use-case. The individual post metadata have been re-implemented in separate widgets, and `PostCardMetadata` composes it's widget from those individual metadata widgets. This allows us to add even more types of widgets in the future if we decide to.
- A new settings widget was created to handle drag and drop capabilities for the individual metadata widgets. Currently, only drag and drop is working as intended. You cannot re-organize the widgets within the DragTarget as implementation for that seems to be a bit tricky.

This is still in draft as there's some cleanup that needs to be addressed (localization strings, general code cleanup) and the card view settings have yet to be implemented in.

I would like to get some feedback on this implementation if possible (e.g., placement of settings, visual UI/UX, general thoughts)! @micahmo @machinaeZER0 @ggichure

## Issue Being Fixed

Issue Number: N/A

## Screenshots / Recordings

Here is a preview of how the settings drag and drop interface works.

https://github.com/thunder-app/thunder/assets/30667958/8284d104-922a-4a3f-867e-c2f08d94997a

## Checklist

- [ ] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by hjiangsu** [comment]
I got this idea from Mlem - I saw it in their app and thought it was a really cool idea! I'll try to post a video of how they implement this. Theirs is a bit more refined in that you can adjust the metadata around once you add it in. Thats the final effect I'd like to achieve, but it seems a bit tricky!

https://github.com/thunder-app/thunder/assets/30667958/865ded7e-b799-42b9-8db2-eb1264c1fac9

**Comment by hjiangsu** [comment]
Some more recordings on the overall UI/UX! There's a slight issue with the community icon on the card preview which I'll fix!

Let me know your thoughts, I'm still very much open to changing the overall look based on feedback

https://github.com/thunder-app/thunder/assets/30667958/c9483d58-d0fc-400f-9d26-04427a99b0eb

https://github.com/thunder-app/thunder/assets/30667958/db557912-feb7-4fdd-bcfa-682cb41b3f0d

**Comment by micahmo** [comment]
It looks awesome!

The only feedback I have is that, seeing the widgets in their own little chip makes me wonder if that would actually be an improvement for the final UI! Haha! I know that wasn't your intention, but I kind of like the look. It helps to separate the data so it doesn't all run together. Maybe it could be an option.

But for your goal for this PR, I love it.

**Comment by hjiangsu** [comment]
> The only feedback I have is that, seeing the widgets in their own little chip makes me wonder if that would actually be an improvement for the final UI!

I was messing around with the UI to see how it would be with the chips, but I feel like there's so little horizontal real estate that it makes it more difficult to accomplish well 😆. We can add this in as an option if interested though in a different PR!

P.S. I really like having all the information be displayed in one line, rather than it wrapping around since it feels cleaner!

**Comment by hjiangsu** [comment]
I believe this should be good for review now! Let me know how everything feels and if you'd like me to make any changes to this! @micahmo @ggichure 

Note: There are some changes to the minimum iOS deployment target - I believe this was automatically changed when I updated flutter on my end (to version 3.16.9)

**Review by micahmo — APPROVED** [review]
Looks awesome!

**Review by ggichure — APPROVED** [review]

**Comment by machinaeZER0** [comment]
Sorry for completely missing the discussion here, but this is incredible! Nice work!

**Pull request merged**
