### PR TITLE
setting to show/hide user avatars in comments and posts

### PR DESCRIPTION
**Pull request by ggichure**
## Pull Request Description

This PR adds settings  to show/hide user avatars in comments and posts. 

## Issue Being Fixed

Issue Number: #600 

## Screenshots / Recordings

|                                |                                |
|:------------------------------:|:------------------------------:|
| Screenshot_20240128-084320_Thunder | Screenshot_20240128-084341_Thunder |
| Screenshot_20240128-084441_Thunder | Screenshot_20240128-084502_Thunder |

ww

## Checklist

- [x] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by ggichure** [comment]
Didn't take into account , Community avatars. I'll scale this down to only comments for now. 
Community Avatars and UserAvatars appear in the same area. 
Any ideas on how to separate this are welcome. @hjiangsu @micahmo .

**Comment by ggichure** [comment]
@micahmo  @hjiangsu  `CommunityAvatar` and  `UserAvatar` Appear in the same place. 
Any UI thoughts on how we could go about this?

**Comment by micahmo** [comment]
> @micahmo @hjiangsu `CommunityAvatar` and `UserAvatar` Appear in the same place. Any UI thoughts on how we could go about this?

Can you post a screenshot of this? Thanks!

**Comment by ggichure** [comment]
Done in #1300

**Pull request closed without merging**
