### PR TITLE
Ability to select app language

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This is a PR which introduces the ability to select Thunder's localization language from the Settings page.

This PR changes/introduces a couple new things:
- It sorts all the `.arb` files to be alphabetical in order. When adding new translation strings, attempts should be made to ensure it stays in alphabetical order. I have locked Weblate translations temporarily until this is merged in and Weblate is synced up with the .arb changes.
- A new `LanguageLocal` class was added in to help translate language codes to the respective names
- Added a new package `l10n_esperanto` to help with the Esperanto localization. Android does not natively support this, so this localization is not part of the default flutter localization packages.

## Issue Being Fixed

Issue Number: #899

## Screenshots / Recordings

https://github.com/thunder-app/thunder/assets/30667958/241e255e-7b67-4aa9-b079-0098afae31e1

## Checklist

- [x] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [x] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by hjiangsu** [comment]
@micahmo This is ready for review if you'd like to do a quick test on it!

**Review by micahmo — APPROVED** [review]
LGTM!

We might have some RTL issues, but that's separate. 😊

Are we missing a language in the UI?

| image |
| - |

image

**Comment by hjiangsu** [comment]
> Are we missing a language in the UI?

Good catch, let me double check that!

**Comment by hjiangsu** [comment]
Should be good now! I double all the files with https://github.com/thunder-app/thunder/tree/translations/lib/l10n to just make sure we have all the translations in place.

**Review by micahmo — APPROVED** [review]

**Pull request merged**
