### PR TITLE
#117 request focus search page

### PR DESCRIPTION
**Pull request by ggichure**
#117 request focus search page using `FocusManager`

### CODE REVIEW

**Comment by hjiangsu** [comment]
It looks good! Just one question - why was pubspec.lock removed?

**Comment by ggichure** [comment]
> why was pubspec.lock removed?

Force of habit.

**Comment by micahmo** [comment]
@ggichure Do we still need this now that #494 is done?

**Comment by hjiangsu** [comment]
I'll close this as there has been no activity and this should be added in with #494!

**Pull request closed without merging**
