### PR TITLE
Sidebars

### PR DESCRIPTION
**Pull request by CTalvio**
Adds sidebars accessible on community pages and user profiles.

- #368 
Adds the ability to block and unblock a user on their profile page.

Known problems:
- Currently does not check if a user is already blocked when opening their sidebar.
- Local instance information is not available.

Fixing these will have to be done by someone else, or me, later. I'm done with this for now, but I've gotten it to a very usable state.

### CODE REVIEW

**Comment by CTalvio** [comment]
#289

**Comment by machinaeZER0** [comment]
I've been thinking about the sidebar some more and I have a thought/request - would it be possible to change the arrow icon that opens the sidebar to an information icon? The old lowercase i within a circle. 

My thinking here is that while the arrow indicates that something will happen when you tap it, it doesn't inform them as to what specifically will happen. If we use an information icon instead, people will tap on it expecting more information and then be pleasantly surprised by the beautiful sidebar, is my thinking.

If we made this change I don't think we'd necessarily need an arrow icon to close the sidebar either - we don't have one to close the left sidebar, after all. When people are done sidebar-ing they can just swipe the bar away :)

cc @hjiangsu @micahmo and others in case people have further thoughts on this

**Comment by micahmo** [comment]
I had originally suggested [menu_open_rounded](https://api.flutter.dev/flutter/material/Icons/menu_open_rounded-constant.html) which I liked because it indicated both an action (with the arrow) and the result (that it would show a menu).

We could definitely use an info icon though, like [info_outline_rounded](https://api.flutter.dev/flutter/material/Icons/info_outline_rounded-constant.html).

**Comment by CTalvio** [comment]
I ended up not using the icon you found, I also liked it better, but at a size where it looked right, it was too small, and a size where it was big enough to be noticeable, it looked very "bloated".

Replacing the arrow, or adding the info icon, could work.

**Comment by CTalvio** [comment]
Ready to merge! @hjiangsu 

image

I can swap that icon in again if we end up preferring.

**Pull request merged**
