### PR TITLE
Combine theme options into a list

### PR DESCRIPTION
**Pull request by coslu**
Combines the individual toggle options for system theme, dark theme and pure black theme into a `ListOption`. 

The toggles were always overriding each other, which could be confusing, and only one of system/light/dark/black would be active at a time, so a list made more sense.

Also changes the default theme to system instead of dark. 

Here is how it looks: 

Screenshot_20230712_232702

### CODE REVIEW

**Comment by micahmo** [comment]
Very nice, this was much needed!

**Comment by machinaeZER0** [comment]
This looks great! I haven't looked at the code, just the screenshot - should the icons for dark and black mode be more differentiated? In the current version they are different (though they definitely could be differentiated further)

**Comment by coslu** [comment]
Good idea. This looks better, right?

Screenshot_20230713_201905

**Comment by hjiangsu** [comment]
Yup, I think that looks good!

**Pull request merged**
