### PR TITLE
Upgrade dependencies for Flutter 3.27

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR upgrades our packages and dependencies to be compatible with Flutter 3.27! To read more about the changes in 3.27, see https://medium.com/flutter/whats-new-in-flutter-3-27-28341129570c

One notable change here is that Flutter 3.27 now uses Impeller as the default rendering engine on Android, which should hopefully improve the overall smoothness and experience on Android devices!

I'll also have a follow-up PR to update our CI to use 3.27 once this is merged in

## Issue Being Fixed

Issue Number: N/A

## Checklist

- [ ] If a new package was added, did you ensure it uses an appropriate license and is actively maintained?
- [ ] Did you use localized strings (and added appropriate descriptions) where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by hjiangsu** [comment]
I'll go ahead and merge this in as it's a blocker (I'm unable to run builds locally since I upgraded to 3.27). Do let me know if there are any issues that come up from this though!

**Comment by micahmo** [comment]
> Flutter 3.27 now uses Impeller as the default rendering engine on Android

Nice!!

**Comment by micahmo** [comment]
Hey @hjiangsu just a heads up that I noticed a small UI issue which I assume is related to this change. Some places with icon buttons seem have much smaller icons now, such as...
- the top row of actions in both the post and comment bottom sheet
- the star button for communities in the sidebar

That's all I've noticed so far but I'll update if I see ant thing else.

I haven't looked at the code yet, but I'm guessing these are all `IconButton` widgets with a custom size.

**Comment by micahmo** [comment]
Hey @hjiangsu just a heads up that I noticed a small UI issue which I assume is related to this change. Some places with icon buttons seem have much smaller icons now, such as...
- the top row of actions in both the post and comment bottom sheet
- the star button for communities in the sidebar

That's all I've noticed so far but I'll update if I see anything else.

I haven't looked at the code yet, but I'm guessing these are all `IconButton` widgets with a custom size.

**Pull request merged**
