### PR TITLE
Added Polish locale

### PR DESCRIPTION
**Pull request by Pazdikan**
## Pull Request Description
I've added the polish locale

## Issue Being Fixed

Issue Number: N/A

## Checklist

- [x] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by micahmo** [comment]
Hey @Pazdikan, thank you so much for this awesome contribution!

@hjiangsu recently merged several PRs which introduced new resource strings. Would you be willing to take a quick peek and, if you have time and willingness, include and translate those as well? If not, we'll just have to put default (English) strings in this file. Let us know either way, and thanks again!

**Comment by Pazdikan** [comment]
Sure, I'll look into that

**Comment by Pazdikan** [comment]
Hey @micahmo, I've updated the locale with new strings.
Let me know if I missed something.

**Review by micahmo — APPROVED** [review]
LGTM! Thanks again!

**Pull request merged**
