### PR TITLE
Improve comment/post actions

### PR DESCRIPTION
**Pull request by micahmo**
## Pull Request Description

This PR updates the Post and Comment actions to bring them more in parity with other functionality in the app and with each other.

> Review without whitspace.

#### Post - Added
 - Block User

#### Comment - Changed
 - Moved Share to top row (like Posts) to make room for more options

#### Comment - Added
 - Visit User Profile
 - Block User
 - Visit Instance
 - Block Instance (when supported)

I also added a Block/Unblock Instance to the Visit Instance page (when supported).

> P.S. In a future update, I would like to replace "user"/"community", etc. with the actual names.

## Issue Being Fixed

Issue Number: N/A

## Screenshots / Recordings

https://github.com/thunder-app/thunder/assets/7417301/37ee7e91-ec33-4361-970d-0bb2562a453f

## Checklist

- [x] Did you update CHANGELOG.md?
- [ ] Did you use localized strings where applicable?
- [ ] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by machinaeZER0** [comment]
This is nice! I will say, as the list of things we can do on long press grows, it might make sense to start consolidating similar actions? Boost has a setup like this that i like quite a bit, though for some reason it's not accessed through a long press. Screenshots below:

Screenshot_20231205-230203
and on pressing one of the option groups:
Screenshot_20231205-230215

Thoughts on trying something similar here? I could see grouping the options above into "View..." (personal preference over Visit) and "Block...", or keep the Visit actions exposed and just consolidate the Block actions (the way Boost does).

The biggest benefit is saving space while keeping taps minimal - and that space could eventually be used to add other options like Boost's menu has, such as reporting/sharing/saving/etc (if desired). Would love to hear your thoughts!

**Comment by micahmo** [comment]
> it might make sense to start consolidating similar actions

We can definitely work on optimizing the long-press menu. We already moved several options to the top row (imagine how big it would be if each of those were a separate row!). There are a couple approaches to take. Like Boost, we could group things by action. Sync takes a slightly different approach and groups things by entity (for example, you'd click on the person first, then you could block, visit, etc.).

It would be nice if we could minimize taps instead of requiring a second menu. At one point I tried putting secondary action buttons in the same row, like this (if you can picture what I mean). But it got a little too busy.

| Actions | |
|--------|--------|
| Visit Profile | 🚫 |
| Visit Community | 🚫 |

Anyway, as usual, we can get this PR in first with the functionality, and then discuss a possible UI upgrade! If anyone wants to make mockups, that could help a lot!

**Comment by machinaeZER0** [comment]
For what it's worth, I actually primarily use the long press menu to block communities as I'm browsing the main feed, so I love that we currently have it exposed! Hear what you're saying though :)

**Comment by hjiangsu** [comment]
Linking this issue as it relates to this: #253

**Pull request merged**
