### PR TITLE
Add additional account settings

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR adds a bunch of additional account settings that sync up with Lemmy, including:
- Display name
- Profile bio
- Email
- Matrix user ID
- Default feed type - this setting will override the existing app setting
- Default feed sort - this setting will override the existing app setting
- Show NSFW content

As a result of this, I also cleaned up the user settings page and moved discussion languages and blocking to separate pages.

Note: I opted to only sync settings that adjust underlying logic. I left out most of the settings which change the UI in some way (since I believe that's better handled in the app settings). These are the settings I omitted from including:
- Interface language
- theme
- Blur NSFW content
- Auto-expand media
- Show Avatars
- Bot account toggle
- Show notifications for new posts
- Send notifications to email
- Open links in a new tab

Some settings that are still missing but would be good to add in the future include:
- Avatar
- Banner
- Two-factor auth
- Exporting/importing settings

I did some basic testing for all of the new settings introduced, but there might still be some edge cases I missed!

## Issue Being Fixed

Issue Number: N/A

## Screenshots / Recordings

**Account Settings**

https://github.com/thunder-app/thunder/assets/30667958/e5db433f-e823-4ec9-a342-8156c76960e4

**Discussion Languages**

https://github.com/thunder-app/thunder/assets/30667958/b72b3ced-bfee-43ab-a05c-c21fa98fc50f

**Block Management**

https://github.com/thunder-app/thunder/assets/30667958/f75ffa7c-364b-4374-8c69-84292c1c61f1

**Feed Account Sort/Type**
Keep an eye out on the feed sort type

https://github.com/thunder-app/thunder/assets/30667958/c40af8cf-eae6-44ef-a34a-b395c56354a4

## Checklist

- [ ] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [x] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Review by micahmo — APPROVED** [review]
This is awesome! I love all the new settings, the reorganization of the content management section, the use of the FAB and tabs.

Here are just a few initial thoughts from watching the demo videos. Any/all of these things can be separate.
* In General Settings, should "Default Comment Sort Type" go under "Comments" rather than "Feed"?
* In the list of settings you said you didn't add because they mostly related to the web UI, one I disagree with is "Bot account toggle" which marks your own account as being a bot. I see a lot of people have this on by accident, so it might be nice to allow it to be toggled off in Thunder.
* I believe bios support markdown, so you might want to consider sanitizing the content for the subtitle. You might also want to truncate it, since bios may be long.

**Comment by hjiangsu** [comment]
Alright, I addressed most of the comments you had!
- Moved "Default Comment Sort Type" top "Comments"
- Added "Bot" to user account settings

> I believe bios support markdown, so you might want to consider sanitizing the content for the subtitle. You might also want to truncate it, since bios may be long.

For this, I expanded the text field to allow for multiple lines, and truncated/sanitized the bio preview. For now, it's still using a simple text field even though markdown is supported but we can add in markdown support for bios in a future PR!

**Comment by micahmo** [comment]
Awesome, the changes look good!!

**Comment by micahmo** [comment]
@hjiangsu I noticed a slight quirk here.

| image |
| - |

**Pull request merged**
