### PR TITLE
update-tr-language

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by hjiangsu** [comment]
Hey! Thanks for doing this - I would like to suggest using Weblate instead to add in translations, mainly because it makes it easier to merge in changes which passes the CI tests.

Here is the Weblate link for Turkish if you're interested: https://hosted.weblate.org/projects/thunder/thunder/tr/

**Comment by mikropsoft** [comment]
> Hey! Thanks for doing this - I would like to suggest using Weblate instead to add in translations, mainly because it makes it easier to merge in changes which passes the CI tests.
> 
> Here is the Weblate link for Turkish if you're interested: https://hosted.weblate.org/projects/thunder/thunder/tr/

I didn't use weblate because I wanted to make a complete change. I cannot upload files. But this is possible for crowdin.

**Comment by hjiangsu** [comment]
Ahh alright - in this case, there are some errors in the CI that have to be addressed first before I can merge this in! The errors are listed here: https://github.com/thunder-app/thunder/actions/runs/9724452159/job/26840674082?pr=1473

From a quick look of things, it seems like it might just be due to issues with incorrectly using Turkish for the placeholders. For example, there are some strings which have placeholders written in between curly braces `{placeholder}`. In these cases, we want to keep the placeholder value untranslated.

Here's an example of what I mean (`visibility` is a placeholder here):

```
// Original
"visibility": "Visibility: {visibility}",

// Correct Translation
"visibility": "Görünürlük: {visibility}",

// Incorrect Translation
"visibility": "Görünürlük: {görünürlük}",
```

Let me know if you need any more clarification on this, and thanks again for helping with translations!

**Comment by mikropsoft** [comment]
> Ahh alright - in this case, there are some errors in the CI that have to be addressed first before I can merge this in! The errors are listed here: https://github.com/thunder-app/thunder/actions/runs/9724452159/job/26840674082?pr=1473
> 
> From a quick look of things, it seems like it might just be due to issues with incorrectly using Turkish for the placeholders. For example, there are some strings which have placeholders written in between curly braces `{placeholder}`. In these cases, we want to keep the placeholder value untranslated.
> 
> Here's an example of what I mean (`visibility` is a placeholder here):
> 
> ```
> // Original
> "visibility": "Visibility: {visibility}",
> 
> // Correct Translation
> "visibility": "Görünürlük: {visibility}",
> 
> // Incorrect Translation
> "visibility": "Görünürlük: {görünürlük}",
> ```
> 
> Let me know if you need any more clarification on this, and thanks again for helping with translations!

I think fixed now.

**Comment by hjiangsu** [comment]
I just fixed a couple of more build errors. It should be good to go now. Thanks again!

**Review by hjiangsu — APPROVED** [review]

**Pull request merged**
