### PR TITLE
Add setting to show or hide read posts

### PR DESCRIPTION
**Pull request by hjiangsu**
## Pull Request Description

This PR introduces a setting to toggle on and off read posts which syncs up with the currently active Lemmy account. I've added the general logic to allow fetching and updating the current user's account settings. This will allow us to more easily add in options in the future on a per-account basis.

Since this setting is synced with the Lemmy account, there's no additional logic required to check if the given post being fetched has been read or not.

An idea for a future improvement would be a account selector within this page to allow us to switch between the different logged-in accounts.

## Issue Being Fixed

Issue Number: #913

## Screenshots / Recordings

| 0.18.x | 0.19.x |
|-|-|
|simulator_screenshot_1F989691-6976-4D76-BF42-95C51D50D8F5|simulator_screenshot_ACF0A276-89B1-4B04-809F-AB6FD06E127C|

## Checklist

- [ ] Did you update CHANGELOG.md?
- [x] Did you use localized strings where applicable?
- [x] Did you add `semanticLabel`s where applicable for accessibility?

### CODE REVIEW

**Comment by micahmo** [comment]
Looks great!

Would it make sense to shrink some of the space here so that elements are relatively evenly spaced?

| image |
| - |

Also for identifying the current user, would it make sense to show the whole user widget like we do in the Create Post page?

**Comment by hjiangsu** [comment]
> Would it make sense to shrink some of the space here so that elements are relatively evenly spaced?

I noticed that too - I can see if I can shrink it down a bit more!

> Also for identifying the current user, would it make sense to show the whole user widget like we do in the Create Post page?

Good idea, I'll see if I can add that in quickly

**Comment by micahmo** [comment]
Looks great!

I wonder if we even need the "you are current viewing..." or if it would be sufficient to have the user widget at the top (maybe above the first paragraph). But I'll leave that up to you. It's good as is!

**Comment by hjiangsu** [comment]
Done, removed current user text and moved the user indicator to the top of the page!
simulator_screenshot_EFC01939-3D20-4CDB-AAEA-692F0F670759

**Comment by micahmo** [comment]
Yeah that looks really nice!!

P.S. It looks like there's an error on this page in 0.19. Not sure if it's new, so it can probably be addressed separately.

**Comment by hjiangsu** [comment]
> P.S. It looks like there's an error on this page in 0.19. Not sure if it's new, so it can probably be addressed separately.

Hmm, what's the error? I can't reproduce it on my end

**Comment by micahmo** [comment]
> Hmm, what's the error? I can't reproduce it on my end

Voyager seems to be having some issues at the moment, so I can't log in, but I will try again when I can!

**Comment by micahmo** [comment]
Here you go, let me know if this helps!

https://github.com/thunder-app/thunder/assets/7417301/fa5b9c60-af78-487a-8e68-e9fc621d0d05

**Comment by hjiangsu** [comment]
Just curious, but are you able to login to voyager.lemmy.ml (on the web UI)? I think the server was reset a while back so all existing accounts there were deleted.

I had to create a new account to log in because I had issues using my old credentials.

**Comment by micahmo** [comment]
Yes I also had to recreate my account a while back, and yes I can still log into the web UI. However, I tried logging out in Thunder and back in, and that seemed to fix the issue. So I'll just blame it on some Voyager weirdness. 😊 Thanks!

**Pull request merged**
