### PR TITLE
Automatically populate Lemmy domains in Android manifest

### PR DESCRIPTION
**Pull request by micahmo**
## Pull Request Description

This PR goes along with #832 and adds support for updating the Android manifest file with Lemmy domains automatically.

### CODE REVIEW

**Comment by ggichure** [comment]
Is it possible to order the instances alphabetically?

**Comment by micahmo** [comment]
> Is it possible to order the instances alphabetically?

Yes they should be alphabetical after this workflow runs! See [instances.dart](https://github.com/thunder-app/thunder/blob/develop/lib/instances.dart).

**Comment by micahmo** [comment]
This should be good to go now that #832 is done!

**Review by ggichure — APPROVED** [review]
LGTM

**Review by hjiangsu — APPROVED** [review]
LGTM!

**Pull request merged**
