### PR TITLE
Improve settings page

### LINKED ISSUE #296: Grey out/lock options that don't apply to current settings (view/theme)
This might also make sense to couple with a restructuring of the General settings page, but I think in general it might make sense to grey out options that don't pertain to your current settings - disabling settings that apply only to Normal view when Compact is toggled, and vice versa, as well as theme settings

Probably super low priority, but feels like it would be a nice touch at some point :)

### PR DESCRIPTION
**Pull request by CTalvio**
I've cleaned up and categorized the different options currently available on the "General" settings page.

Comment related toggles are now in a "Comments" section, settings that apply to the feed, have been moved to "Feed" rather than "Posts".

The compact switch now has a "subsection" that only shows settings that apply to the currently selected view option. And look at that! I animated my first thing!

[Kazam_screencast_00000.webm](https://github.com/hjiangsu/thunder/assets/4365015/994bece7-9065-4351-88f6-89876f91cd39)

Closes #296

### CODE REVIEW

**Comment by machinaeZER0** [comment]
This is so rad! Nice work!

**Comment by CTalvio** [comment]
Gonna add a couple more things, so hold off on merge @hjiangsu for now.

**Comment by hjiangsu** [comment]
I am digging the animations on that, it looks really good! I'll hold off for now as you said, but let me know when you're ready for me to take a look!

**Comment by jordan1776** [comment]
I like the organization and the hideaway for the compact/normal view settings is pretty clever, but  I still feel that the views settings be moved out of general. This might be a sperate PR for the future. #242

**Comment by machinaeZER0** [comment]
I was actually thinking that too! Maybe changing Theming to Appearance, to combine theme and view options? Further down the line, I mean. 

Could also see moving some of the gesture toggles in General over to the Gesture menu?

**Comment by jordan1776** [comment]
>Maybe changing Theming to Appearance, to combine theme and view options?

That makes sense since font sizes probably should be defined per view.

**Comment by CTalvio** [comment]
> Could also see moving some of the gesture toggles in General over to the Gesture menu?

Done

image

**Comment by CTalvio** [comment]
@hjiangsu Ok now this is ready to merge.

**Pull request merged**
