### PR TITLE
Link preview for compact view

### PR DESCRIPTION
**Pull request by CTalvio**
Also removes the "thumbnails" on text posts, allowing long titles to overflow to fewer lines

image

image

### CODE REVIEW

**Comment by CTalvio** [comment]
Closes #91

**Comment by micahmo** [comment]
Very nice!!

I'm a little torn on removing the placeholder for text posts. Yes, it doesn't really accomplish anything, but it keeps the UI very uniform.

Either way, nice changes.

**Comment by CTalvio** [comment]
> Very nice!!
> 
> I'm a little torn on removing the placeholder for text posts. Yes, it doesn't really accomplish anything, but it keeps the UI very uniform.
> 
> Either way, nice changes.

If aiming for minimalism, and you come to a cross-roads between the aesthetic and functional...

Always pick functional. Minimalism is about necessity, and the beauty that of serving that above all else.

**Comment by hjiangsu** [comment]
> I'm a little torn on removing the placeholder for text posts. Yes, it doesn't really accomplish anything, but it keeps the UI very uniform.

I'm indifferent about this - I like the uniformity as you mentioned, but also understand that it takes up a lot of screen width to have something that doesn't have much use (aside from keeping everything uniform)

 I'll go ahead and merge this in, and if anything, we'll get more feedback from the community if this is a big issue!

**Comment by machinaeZER0** [comment]
I agree with @micahmo on uniformity (and I also kinda liked the text post box/icon) but I don't feel too strongly about it at the end of the day :)

**Comment by micahmo** [comment]
> I agree with @micahmo on uniformity (and I also kinda liked the text post box/icon) but I don't feel too strongly about it at the end of the day :)

Maybe it can be added back as an option. 😊

**Pull request merged**
